### ISSUE TITLE
'ConnectionService' object has no attribute 'connection_provider'

### ISSUE THREAD

**Issue by muhammetbolat** [PythonDataIntegrator/pythondataintegrator#23]
Hello Guys,

I have already found an AttributeError in CheckDatabaseConnectionResource.py (line 29).

`connection_manager = self.connection_service.connection_provider.get_connection_manager(connection=connection)`

connection_service is an instance of ConnectionService and you try to reach connection_provider variable but it is failed. There is no attribute is defined in ConnectionService as connection_provider.

Thx.

**Comment by ahmetcagriakca** [comment]
Muhammet this improvment seems to be affected by connection secret implementations. While solving the error here, we can make arrangements by moving it to the domain layer.
